# Generated by Django 3.2 on 2023-06-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCon',
            fields=[
                ('id', models.CharField(max_length=8192, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': '内容列表',
                'verbose_name_plural': '内容列表',
            },
        ),
    ]
